name: Capture The Flag
baseurl: http://capstone-ua-redepsilon.github.io/projectred/
description: a synchronous, cooperative multiplayer, puzzle platformer game for Android

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md']
